# Generated by Django 6.1.1 on 2026-09-26 15:14

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 26, 15, 14, 17, 981316, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journey',
            name='current_stage',
            field=models.CharField(choices=[('admission', 'Admission'), ('investigation', 'Investigation'), ('procedure', 'Procedure'), ('recovery', 'Recovery'), ('discharge', 'Discharge')], default='admission', max_length=30),
        ),
        migrations.AlterField(
            model_name='journeystagelog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
