# Generated by Django 6.1.1 on 2026-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='network_insurers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
