# Generated by Django 6.1.1 on 2026-09-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_alter_hospital_network_insurers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='empanelled_schemes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
