# Generated by Django 6.1.1 on 2026-09-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_hospital_empanelled_schemes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='ownership_type',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('trust', 'Trust/Charitable')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='empanelled_schemes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='network_insurers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='category',
            field=models.CharField(choices=[('general_ward', 'General Ward'), ('semi_private', 'Semi-Private (2-bed)'), ('private', 'Private (Single Occupancy)'), ('deluxe', 'Deluxe/Super Deluxe'), ('suite', 'Suite'), ('icu', 'ICU (Intensive Care Unit)'), ('icu_hdu', 'HDU (High Dependency Unit)'), ('nicu', 'NICU (Neonatal ICU)'), ('picu', 'PICU (Pediatric ICU)'), ('ccu', 'CCU (Cardiac Care Unit)'), ('day_care', 'Day Care (No overnight stay)')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('hospital', 'category')},
        ),
    ]
