# Generated by Django 6.1.1 on 2026-09-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_ownership_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='category',
            field=models.CharField(choices=[('general_ward', 'General Ward'), ('semi_private', 'Semi_Private (2-bed)'), ('private', 'Private (Single Occupancy)'), ('deluxe', 'Deluxe/Super Deluxe'), ('suite', 'Suite'), ('icu', 'ICU (Intensive Care Unit)'), ('icu_hdu', 'HDU (High Dependency Unit)'), ('nicu', 'NICU (Neonatal ICU)'), ('picu', 'PICU (Pediatric ICU)'), ('ccu', 'CCU (Cardiac Care Unit)'), ('day_care', 'Day Care (No overnight stay)')], max_length=50),
        ),
    ]
