# Generated by Django 6.1.1 on 2026-09-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer', models.CharField(max_length=255)),
                ('scheme_type', models.CharField(choices=[('private', 'Private'), ('ESI', 'ESI'), ('PM-JAY', 'PM-JAY'), ('state_scheme', 'State\tScheme')], max_length=20)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('room_eligibility', models.JSONField()),
                ('covered_procedures', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('co_pay_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
