# Generated by Django 6.1.1 on 2026-09-28 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('insurer_type', models.CharField(choices=[('private', 'Private Insurer'), ('government', 'Government Scheme')], default='private', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='policy',
            name='scheme_type',
            field=models.CharField(choices=[('private', 'Private'), ('ESI', 'ESI'), ('PM-JAY', 'PM-JAY'), ('state_scheme', 'State Scheme')], max_length=20),
        ),
        migrations.CreateModel(
            name='PolicyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scheme_type', models.CharField(choices=[('private', 'Private'), ('ESI', 'ESI'), ('PM-JAY', 'PM-JAY'), ('state_scheme', 'State Scheme')], max_length=20)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('room_eligibility', models.JSONField()),
                ('covered_procedures', models.JSONField(default=list)),
                ('exclusions', models.JSONField(default=list)),
                ('co_pay_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='insurance.insurer')),
            ],
            options={
                'unique_together': {('insurer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='insurance.policyplan'),
        ),
    ]
